# General
bindkey -e
zstyle :compinstall filename '/home/chiyonn/.zshrc'
autoload -Uz compinit
compinit


### Aliases
ALIASES_FILE=$HOME/.aliases
if [ -f "$ALIASES_FILE" ]; then
    source "$ALIASES_FILE"
fi


### History
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=10000


### Git
# Prompt
GIT_PROMPT_SCRIPTFILE=$HOME/.zsh/git-prompt.sh
if [ -f "$GIT_PROMPT_SCRIPTFILE" ]; then
    source "$GIT_PROMPT_SCRIPTFILE"
fi

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM=auto

setopt PROMPT_SUBST

PS1='%F{blue}%n@%m%f:%F{cyan}%~%f %F{yellow}$(__git_ps1 "(%s)")%f
%F{green}$%f '
RPS1='%F{white}[%*]%f'

# Completion
fpath=(~/.zsh $fpath)

zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash

# Sync Check
DOTS_REPO_DIRPATH=$HOME/Projects/Dotty-McDotface
if [ -d "$DOTS_REPO_DIRPATH" ]; then
    source "$DOTS_REPO_DIRPATH/git_sync_check.sh"
fi
